import { test, expect } from '@playwright/test'
import { createStaffViaApi, launchApp, waitForText } from './helpers'

test.describe('Dashboard Output Finder', () => {
  test('opens outputs dialog from staff actions menu', async () => {
    const { page, cleanup } = await launchApp()

    try {
      // Skip wizard
      await waitForText(page, 'Welcome to OpenStaff')
      await page.click('text=Get Started')
      await page.click('text=Skip')
      await page.click('text=Go to Dashboard')

      await waitForText(page, 'Dashboard', 15000)

      await createStaffViaApi(page, {
        name: 'Output Finder Staff',
        role: 'Output test role',
        gather: 'Check outputs',
        execute: 'Write outputs',
        evaluate: 'Review outputs'
      })

      await page.reload()
      await waitForText(page, 'Output Finder Staff', 15000)

      const row = page.locator('tr', { hasText: 'Output Finder Staff' }).first()
      await row.locator('button[aria-label="Staff actions"]').click()
      await page.getByRole('menuitem', { name: 'View Outputs' }).click()

      await expect(page.getByRole('dialog')).toContainText('Outputs - Output Finder Staff')
      await expect(page.getByRole('dialog')).toContainText('CLAUDE.md')
      await expect(page.getByRole('dialog')).toContainText('Auto-generated by OpenStaff')
    } finally {
      await cleanup()
    }
  })
})
