import { describe, it, expect } from 'vitest'
import { generateClaudeMd } from './template-generator'
import type { StaffConfig } from '@shared/types'

describe('template-generator', () => {
  const baseConfig: StaffConfig = {
    id: 'test-staff',
    name: 'Test Staff',
    role: 'Test role for unit testing',
    gather: 'Gather test data from sources',
    execute: 'Execute test tasks based on gathered data',
    evaluate: 'Evaluate results and learn',
    kpi: 'KPI > 90%',
    agent: 'claude-code',
    model: 'claude-sonnet-4-5',
    skills: ['test-skill'],
    created_at: '2026-01-01T00:00:00Z'
  }

  it('generates CLAUDE.md with staff name as title', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('# Test Staff')
  })

  it('includes auto-generated warning', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('Auto-generated by OpenStaff')
    expect(result).toContain('Do NOT edit manually')
  })

  it('includes role', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('Test role for unit testing')
  })

  it('includes gather instructions', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('### 1. Gather')
    expect(result).toContain('Gather test data from sources')
  })

  it('includes execute instructions', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('### 2. Execute')
    expect(result).toContain('Execute test tasks based on gathered data')
  })

  it('includes evaluate instructions', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('### 3. Evaluate')
    expect(result).toContain('Evaluate results and learn')
  })

  it('includes KPI', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('KPI > 90%')
  })

  it('handles empty KPI', () => {
    const config = { ...baseConfig, kpi: '' }
    const result = generateClaudeMd(config)
    expect(result).toContain('No specific KPIs defined')
  })

  it('includes cycle recording instructions', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('cycles.jsonl')
    expect(result).toContain('kpi.jsonl')
    expect(result).toContain('signals.jsonl')
    expect(result).toContain('memory.md')
  })

  it('includes never stop rule', () => {
    const result = generateClaudeMd(baseConfig)
    expect(result).toContain('Never stop working')
  })
})
